# Generated by Django 5.2.7 on 2025-10-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_module', '0002_remove_messages_conversation_remove_messages_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmember',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='message_module.conversation'),
        ),
    ]
