# Generated by Django 5.2.7 on 2025-10-14 15:48

import cloudinary.models
import common.utils.validator_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='postimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[common.utils.validator_image.validate_image_size], verbose_name='image'),
        ),
    ]
