# Generated by Django 5.2.7 on 2025-10-15 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_module', '0002_remove_eventimage_image_url_eventimage_image'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('is_pinned', True)), fields=('is_pinned',), name='unique_pinned_event'),
        ),
    ]
