# Generated by Django 5.2.7 on 2025-10-22 06:16

import cloudinary.models
import common.utils.validator_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_module', '0003_event_is_pinned_event_unique_pinned_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userevent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='community_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[common.utils.validator_image.validate_image_size], verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
