# Generated by Django 5.2.7 on 2025-10-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broadcast_module', '0004_alter_userevent_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
