# Generated by Django 5.2.7 on 2025-10-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_module', '0003_alter_listing_owner'),
        ('marketplace_module', '0004_alter_listing_wishlisted_by'),
    ]

    operations = [
    ]
