# Generated by Django 5.2.7 on 2025-10-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_module', '0003_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
